[build]
  base = "gbv-app"
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Allow client-side Supabase keys in the bundle without failing Netlify's secrets scan
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"
  # Also omit built assets from scanning to prevent false positives
  SECRETS_SCAN_OMIT_PATHS = "dist/**"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200